modelClass: October\Test\Models\Person

form:
    fields:
        name:
            label: Name
            commentAbove: Text field, required. Given name in the first box, preferred name in the second box.

        # Testing form field with no config
        preferred_name:

        # Nullable
        is_married:
            label: Married
            type: dropdown
            emptyOption: Unknown
            options:
                '0': No
                '1': Yes

        # Proxy Fields
        phone[name]:
            span: auto
            label: Phone Name
            comment: Proxy text field for Phone model.

        phone[number]:
            span: auto
            label: Phone Number
            comment: Proxy text field for Phone model.

        phone[created_at]:
            span: left
            label: Phone Created
            comment: Proxy date picker field for Phone model.
            type: datepicker

        # phone[picture]:
        #     label: Picture
        #     span: right
        #     comment: Proxy file upload field for Phone model.
        #     type: fileupload
        #     mode: image
        #     imageHeight: 260
        #     imageWidth: 260

        phone[brand]:
            label: Brand
            span: left
            comment: Proxy dropdown field for Phone model.
            type: dropdown

    tabs:

        fields:

            birth:
                label: Born (Date Time)
                type: datepicker
                tab: Birthday
                minDate: January 01 2015 11:11
                comment: Date cannot be before January 2015, formatted as m-Y-d.
                format: m-Y-d

            birthdate:
                label: Born (Date)
                type: datepicker
                mode: date
                tab: Birthday
                minDate: 1984-04-12
                maxDate: 2014-04-23
                comment: Date must be between April 1984 - 2014.

            birthtime:
                label: Born (Time)
                type: datepicker
                mode: time
                tab: Birthday
                span: auto

            favcolor:
                label: Favorite color
                type: colorpicker
                default: "#27ae60"
                tab: Birthday
                span: auto
